name: release
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: |
          sudo apt install pandoc
      - uses: actions/checkout@v6
      - name: Build HTML Doc
        run: |
          mkdir -p target
          pandoc -f markdown -t html Changelog.md -o target/changelog.html --metadata title="Changelog" --shift-heading-level-by=1 --css=doc/resource/help.css --standalone --embed-resources
          pandoc -f markdown -t html doc/help.md -o "target/XJadeo Video Sync.html" --metadata pagetitle="XJadeo Video Sync" --resource-path=doc --css=resource/help.css --standalone --embed-resources
      - name: Copy scripts
        run: |
          cp -a src/. target
      - name: Show target files
        run: |
          ls -l target
      - uses: actions/upload-artifact@v7
        with:
          name: XJadeo_Video_Sync
          path: target
